services:
  traefik:
    image: traefik:v2.10
    command:
      - "--api.dashboard=true"
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080" # Traefik dashboard
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.dashboard.rule=Host(`traefik.${BASE_DOMAIN:-localhost}`)"
      - "traefik.http.routers.dashboard.service=api@internal"
      - "traefik.http.routers.dashboard.entrypoints=web"

  backend:
    build:
      context: ./server
      dockerfile: Dockerfile
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.backend.rule=Host(`api.${BASE_DOMAIN:-localhost}`)"
      - "traefik.http.routers.backend.entrypoints=web"

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.frontend.rule=Host(`${BASE_DOMAIN:-localhost}`)"
      - "traefik.http.routers.frontend.entrypoints=web"

  iris:
    image: intersystemsdc/iris-community:latest
    container_name: iris-comm
    environment:
      - IRIS_PASSWORD=heslohovnokleslo
      - IRIS_USERNAME=hackjakbrno
      - ISC_DATA_DIRECTORY=/external/dur
    ports:
      - "1972:1972"
      - "52773:52773"
    volumes:
      - ./db-data:/external/dur
    labels:
      - "traefik.enable=false"
